export const AgentsData = [
  {
    id: 1,
    name: "Samantha Jackson",
    propertiesListed: 500,
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=500&fit=crop&crop=face", // Confident professional woman in business attire
    bio: "Samantha Jackson is a seasoned real estate agent with over 12 years of experience in luxury residential properties. Specializing in high-end markets across Lagos and Abuja, she has developed an exceptional ability to match discerning clients with their dream homes. Her expertise extends to property valuation, market trend analysis, and strategic negotiation, having closed over $150 million in property transactions throughout her career. Samantha is known for her personalized approach, ensuring every client receives white-glove service from initial consultation to final closing.",
    languages: ["English", "Spanish", "Yoruba"],
    contacts: [
      { type: "Office", value: "+234 816 356 5026", icon: "HiOutlinePhoneMissedCall" },
      { type: "Mobile", value: "+234 901 234 5678", icon: "HiMiniDevicePhoneMobile" },
      { type: "WhatsApp", value: "+234 803 457 1892", icon: "PiWhatsappLogo" },
      { type: "Email", value: "sam@realestate.com", icon: "HiOutlineMail" },
      { type: "Website", value: "samjackson.com", icon: "CiGlobe" },
      { type: "Instagram", value: "@samanthajackson", icon: "SlSocialInstagram" },
    ],
    socials: {
      instagram: "https://instagram.com/samanthajackson",
      facebook: "https://facebook.com/samanthajackson",
      linkedin: "https://linkedin.com/in/samanthajackson",
      twitter: "https://twitter.com/samanthajackson",
    },
  },
  {
    id: 2,
    name: "Alexander Thompson",
    propertiesListed: 320,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=500&fit=crop&crop=face",
    bio: "Alexander Thompson brings a decade of expertise in commercial real estate and investment properties to the table. With a background in economics and finance, he specializes in helping investors build diversified property portfolios across Nigeria's emerging markets. His analytical approach to market data and deep understanding of ROI metrics have helped clients achieve exceptional returns on their investments. Alexander is particularly skilled in identifying undervalued properties with high growth potential and navigating complex commercial transactions with multiple stakeholders.",
    languages: ["English", "French", "Igbo"],
    contacts: [
      { type: "Office", value: "+234 817 387 4083", icon: "HiOutlinePhoneMissedCall" },
      { type: "Mobile", value: "+234 902 345 6789", icon: "HiMiniDevicePhoneMobile" },
      { type: "WhatsApp", value: "+234 804 567 8901", icon: "PiWhatsappLogo" },
      { type: "Email", value: "alex@realestate.com", icon: "HiOutlineMail" },
      { type: "Website", value: "alexanderthompson.com", icon: "CiGlobe" },
      { type: "Instagram", value: "@alexanderthompson", icon: "SlSocialInstagram" },
    ],
    socials: {
      instagram: "https://instagram.com/alexanderthompson",
      facebook: "https://facebook.com/alexanderthompson",
      linkedin: "https://linkedin.com/in/alexanderthompson",
      twitter: "https://twitter.com/alexanderthompson",
    },
  },
  {
    id: 3,
    name: "Rachel Bransonson",
    propertiesListed: 450,
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop&crop=face", 
    bio: "Rachel Bransonson is a distinguished real estate consultant with 15 years of experience specializing in luxury waterfront properties and gated communities. Her impressive career includes prestigious certifications in property management and real estate law, enabling her to provide comprehensive guidance on complex transactions. Rachel has built an extensive network of international clients and developers, particularly in the high-end residential sector. She is renowned for her meticulous attention to detail, creative problem-solving abilities, and unwavering commitment to exceeding client expectations in every aspect of the property journey.",
    languages: ["English", "German", "Hausa"],
    contacts: [
      { type: "Office", value: "+234 805 678 9012", icon: "HiOutlinePhoneMissedCall" },
      { type: "Mobile", value: "+234 903 456 7890", icon: "HiMiniDevicePhoneMobile" },
      { type: "WhatsApp", value: "+234 805 123 4567", icon: "PiWhatsappLogo" },
      { type: "Email", value: "rachel@realestate.com", icon: "HiOutlineMail" },
      { type: "Website", value: "rachelbransonson.com", icon: "CiGlobe" },
      { type: "Instagram", value: "@rachelbransonson", icon: "SlSocialInstagram" },
    ],
    socials: {
      instagram: "https://instagram.com/rachelbransonson",
      facebook: "https://facebook.com/rachelbransonson",
      linkedin: "https://linkedin.com/in/rachelbransonson",
      twitter: "https://twitter.com/rachelbransonson",
    },
  },
  {
    id: 4,
    name: "Benjamin Okafor",
    propertiesListed: 280,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop&crop=face",
    bio: "Benjamin Okafor is a dynamic real estate professional with 8 years of focused experience in affordable housing and first-time home buyer programs. His passion for helping families achieve homeownership has made him one of the most trusted agents in the middle-income property market. Benjamin excels at breaking down complex mortgage processes and government housing schemes into understandable steps for his clients. He has developed specialized knowledge in property financing options and regularly conducts workshops to educate prospective buyers about the home acquisition process and long-term property investment strategies.",
    languages: ["English", "Yoruba", "Igbo", "Pidgin"],
    contacts: [
      { type: "Office", value: "+234 809 876 5432", icon: "HiOutlinePhoneMissedCall" },
      { type: "Mobile", value: "+234 704 567 8901", icon: "HiMiniDevicePhoneMobile" },
      { type: "WhatsApp", value: "+234 806 234 5678", icon: "PiWhatsappLogo" },
      { type: "Email", value: "benjamin@realestate.com", icon: "HiOutlineMail" },
      { type: "Website", value: "benjaminokafor.com", icon: "CiGlobe" },
      { type: "Instagram", value: "@benjaminokafor", icon: "SlSocialInstagram" },
    ],
    socials: {
      instagram: "https://instagram.com/benjaminokafor",
      facebook: "https://facebook.com/benjaminokafor",
      linkedin: "https://linkedin.com/in/benjaminokafor",
      twitter: "https://twitter.com/benjaminokafor",
    },
  },
  {
    id: 5,
    name: "Chiamaka Adebayo",
    propertiesListed: 380,
       avatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400&h=500&fit=crop&crop=face",
    
    bio: "Chiamaka Adebayo is a visionary real estate developer and agent with over 14 years of comprehensive experience in both residential and commercial property sectors. Her unique background in architecture gives her an exceptional eye for property potential and renovation opportunities. Chiamaka has successfully managed numerous property development projects from conception to completion, specializing in transforming underutilized spaces into premium residential and commercial assets. She is particularly skilled at identifying emerging neighborhoods and advising clients on strategic property investments that align with urban development trends and infrastructure projects.",
    languages: ["English", "Yoruba", "French", "Hausa"],
    contacts: [
      { type: "Office", value: "+234 802 345 6789", icon: "HiOutlinePhoneMissedCall" },
      { type: "Mobile", value: "+234 705 678 9012", icon: "HiMiniDevicePhoneMobile" },
      { type: "WhatsApp", value: "+234 807 345 6789", icon: "PiWhatsappLogo" },
      { type: "Email", value: "chiamaka@realestate.com", icon: "HiOutlineMail" },
      { type: "Website", value: "chiamakaadebayo.com", icon: "CiGlobe" },
      { type: "Instagram", value: "@chiamakaadebayo", icon: "SlSocialInstagram" },
    ],
    socials: {
      instagram: "https://instagram.com/chiamakaadebayo",
      facebook: "https://facebook.com/chiamakaadebayo",
      linkedin: "https://linkedin.com/in/chiamakaadebayo",
      twitter: "https://twitter.com/chiamakaadebayo",
    },
  },
  {
    id: 6,
    name: "David Chen",
    propertiesListed: 420,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop&crop=face", 
    bio: "David Chen is an internationally-minded real estate specialist with 11 years of experience bridging Nigerian and Asian property markets. Fluent in multiple languages and culturally adept, he has become the go-to agent for expatriates and international investors looking to navigate Nigeria's dynamic real estate landscape. David's expertise includes cross-border property transactions, international financing structures, and cultural brokerage services. He has developed sophisticated systems for remote property acquisition and management, making him particularly valuable for overseas-based investors seeking to build Nigerian property portfolios while minimizing operational complexities.",
    languages: ["English", "Mandarin", "Cantonese", "Yoruba"],
    contacts: [
      { type: "Office", value: "+234 808 765 4321", icon: "HiOutlinePhoneMissedCall" },
      { type: "Mobile", value: "+234 706 789 0123", icon: "HiMiniDevicePhoneMobile" },
      { type: "WhatsApp", value: "+234 808 456 7890", icon: "PiWhatsappLogo" },
      { type: "Email", value: "david@realestate.com", icon: "HiOutlineMail" },
      { type: "Website", value: "davidchenproperties.com", icon: "CiGlobe" },
      { type: "Instagram", value: "@davidchenproperties", icon: "SlSocialInstagram" },
    ],
    socials: {
      instagram: "https://instagram.com/davidchenproperties",
      facebook: "https://facebook.com/davidchenproperties",
      linkedin: "https://linkedin.com/in/davidchenproperties",
      twitter: "https://twitter.com/davidchenproperties",
    },
  },
  {
    id: 7,
    name: "Fatima Bello",
    propertiesListed: 350,
    avatar: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=500&fit=crop&crop=face", 
    bio: "Fatima Bello is a highly respected real estate consultant with 9 years of specialized experience in luxury apartment complexes and high-rise residential developments. Her comprehensive understanding of property management, tenant relations, and building maintenance makes her exceptionally qualified to assist both individual buyers and corporate clients. Fatima has developed proprietary market analysis tools that help clients make data-driven decisions about property acquisitions and timing. She is particularly known for her extensive database of pre-vetted properties and her ability to match clients with homes that perfectly align with their lifestyle preferences and long-term financial goals.",
    languages: ["English", "Arabic", "Hausa", "French"],
    contacts: [
      { type: "Office", value: "+234 810 123 4567", icon: "HiOutlinePhoneMissedCall" },
      { type: "Mobile", value: "+234 707 890 1234", icon: "HiMiniDevicePhoneMobile" },
      { type: "WhatsApp", value: "+234 809 567 8901", icon: "PiWhatsappLogo" },
      { type: "Email", value: "fatima@realestate.com", icon: "HiOutlineMail" },
      { type: "Website", value: "fatimabello.com", icon: "CiGlobe" },
      { type: "Instagram", value: "@fatimabello", icon: "SlSocialInstagram" },
    ],
    socials: {
      instagram: "https://instagram.com/fatimabello",
      facebook: "https://facebook.com/fatimabello",
      linkedin: "https://linkedin.com/in/fatimabello",
      twitter: "https://twitter.com/fatimabello",
    },
  },
  {
    id: 8,
    name: "Michael Rodriguez",
    propertiesListed: 290,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop&crop=face",
    bio: "Michael Rodriguez is an innovative real estate strategist with 7 years of experience focusing on sustainable properties and green building technologies. His forward-thinking approach to real estate combines traditional market knowledge with emerging trends in eco-friendly construction and energy-efficient design. Michael has developed specialized expertise in properties with solar installations, water conservation systems, and sustainable materials. He regularly collaborates with architects and environmental consultants to provide clients with comprehensive assessments of property sustainability features and their long-term cost benefits, making him a pioneer in the growing green real estate market segment.",
    languages: ["English", "Spanish", "Portuguese", "Yoruba"],
    contacts: [
      { type: "Office", value: "+234 811 234 5678", icon: "HiOutlinePhoneMissedCall" },
      { type: "Mobile", value: "+234 708 901 2345", icon: "HiMiniDevicePhoneMobile" },
      { type: "WhatsApp", value: "+234 810 678 9012", icon: "PiWhatsappLogo" },
      { type: "Email", value: "michael@realestate.com", icon: "HiOutlineMail" },
      { type: "Website", value: "michaelrodriguez.com", icon: "CiGlobe" },
      { type: "Instagram", value: "@michaelrodriguez", icon: "SlSocialInstagram" },
    ],
    socials: {
      instagram: "https://instagram.com/michaelrodriguez",
      facebook: "https://facebook.com/michaelrodriguez",
      linkedin: "https://linkedin.com/in/michaelrodriguez",
      twitter: "https://twitter.com/michaelrodriguez",
    },
  }
];