export  const projectData = [
    {
      id: 'O1I0',
      name: 'Sunnyvale Heights',
      location: 'Awka, Anambra',
      leader: 'John Doe',
      team: 'Construction Team A',
      startDate: '17/09/2020',
      endDate: '20/10/2025',
      progress: 78,
    },
    {
      id: 'O1I1',
      name: 'Skyline Towers',
      location: 'Calabar, Cross River',
      leader: 'John Doe',
      team: 'Construction Team B',
      startDate: '17/09/2020',
      endDate: '20/10/2025',
      progress: 45,
    },
    {
      id: 'O1I2',
      name: 'Maplewood Residences',
      location: 'Mainland, Lagos',
      leader: 'John Doe',
      team: 'Construction Team C',
      startDate: '17/09/2020',
      endDate: '20/10/2025',
      progress: 30,
    },
    {
      id: 'O1I3',
      name: 'Cedar Grove Estates',
      location: 'Victoria Island, Lagos',
      leader: 'John Doe',
      team: 'Construction Team D',
      startDate: '17/09/2020',
      endDate: '20/10/2025',
      progress: 75,
    },
    {
      id: 'O1I4',
      name: 'Pine Ridge Villas',
      location: 'Lekki, Lagos',
      leader: 'John Doe',
      team: 'Construction Team E',
      startDate: '17/09/2020',
      endDate: '20/10/2025',
      progress: 45,
    },
  ];