export const propertyData = [
    {
      id: 1,
      street: "Adekunle Fajuyi",
      city: "Lagos",
      type: "Buy",
      category: "Apartment",
      price: "₦12,450,000",
      user: "chioma23",
      isFeatured: true,
      status: "Completed"
    },
    {
      id: 2,
      street: "Ahmadu Bello",
      city: "Abuja",
      type: "Rent",
      category: "Duplex",
      price: "₦8,700,000",
      user: "adebola",
      isFeatured: false,
      status: "Pending"
    },
    {
      id: 3,
      street: "Allen Avenue",
      city: "Lagos",
      type: "Buy",
      category: "Duplex",
      price: "₦32,100,000",
      user: "tunde4real",
      isFeatured: true,
      status: "Completed"
    },
    {
      id: 4,
      street: "Awolowo Road",
      city: "Ibadan",
      type: "Rent",
      category: "Apartment",
      price: "₦5,200,000",
      user: "funmilayo",
      isFeatured: false,
      status: "Cancelled"
    },
    {
      id: 5,
      street: "Bourdillon Road",
      city: "Lagos",
      type: "Buy",
      category: "Duplex",
      price: "₦45,000,000",
      user: "chukwudi",
      isFeatured: true,
      status: "Pending"
    },
    {
      id: 6,
      street: "Broad Street",
      city: "Lagos",
      type: "Rent",
      category: "Apartment",
      price: "₦7,800,000",
      user: "nnamdi99",
      isFeatured: false,
      status: "Completed"
    },
    {
      id: 7,
      street: "Dolphin Estate",
      city: "Lagos",
      type: "Buy",
      category: "Apartment",
      price: "₦18,500,000",
      user: "segunade",
      isFeatured: true,
      status: "Pending"
    },
    {
      id: 8,
      street: "Falomo Road",
      city: "Lagos",
      type: "Rent",
      category: "Duplex",
      price: "₦10,200,000",
      user: "omotola",
      isFeatured: false,
      status: "Completed"
    },
    {
      id: 9,
      street: "Ibrahim Taiwo",
      city: "Kano",
      type: "Buy",
      category: "Apartment",
      price: "₦9,750,000",
      user: "ahmed_b",
      isFeatured: false,
      status: "Cancelled"
    },
    {
      id: 10,
      street: "Ikorodu Road",
      city: "Lagos",
      type: "Rent",
      category: "Apartment",
      price: "₦6,300,000",
      user: "grace_2023",
      isFeatured: false,
      status: "Pending"
    },
    {
      id: 11,
      street: "Isaac John",
      city: "Lagos",
      type: "Buy",
      category: "Duplex",
      price: "₦28,400,000",
      user: "kemi_sh",
      isFeatured: true,
      status: "Completed"
    },
    {
      id: 12,
      street: "Kofo Abayomi",
      city: "Lagos",
      type: "Rent",
      category: "Apartment",
      price: "₦7,100,000",
      user: "jide_owo",
      isFeatured: false,
      status: "Pending"
    },
    {
      id: 13,
      street: "Kongo Campus",
      city: "Zaria",
      type: "Buy",
      category: "Apartment",
      price: "₦11,900,000",
      user: "blessing87",
      isFeatured: false,
      status: "Cancelled"
    },
    {
      id: 14,
      street: "Lugard Avenue",
      city: "Abuja",
      type: "Rent",
      category: "Duplex",
      price: "₦14,500,000",
      user: "ekene_p",
      isFeatured: true,
      status: "Completed"
    },
    {
      id: 15,
      street: "Maitama Sule",
      city: "Kano",
      type: "Buy",
      category: "Duplex",
      price: "₦22,700,000",
      user: "lola_cute",
      isFeatured: false,
      status: "Pending"
    },
    {
      id: 16,
      street: "Marina",
      city: "Lagos",
      type: "Rent",
      category: "Apartment",
      price: "₦9,800,000",
      user: "musa_k",
      isFeatured: false,
      status: "Completed"
    },
    {
      id: 17,
      street: "Mobolaji Bank Anthony",
      city: "Lagos",
      type: "Buy",
      category: "Duplex",
      price: "₦38,200,000",
      user: "zainab_o",
      isFeatured: true,
      status: "Cancelled"
    },
    {
      id: 18,
      street: "Murtala Mohammed",
      city: "Kano",
      type: "Rent",
      category: "Apartment",
      price: "₦5,600,000",
      user: "yemi2023",
      isFeatured: false,
      status: "Pending"
    },
    {
      id: 19,
      street: "Nnamdi Azikiwe",
      city: "Enugu",
      type: "Buy",
      category: "Apartment",
      price: "₦15,300,000",
      user: "femi_ade",
      isFeatured: false,
      status: "Completed"
    },
    {
      id: 20,
      street: "Obafemi Awolowo",
      city: "Ibadan",
      type: "Rent",
      category: "Duplex",
      price: "₦12,800,000",
      user: "prince_t",
      isFeatured: true,
      status: "Pending"
    },
    {
      id: 21,
      street: "Oba Akran",
      city: "Lagos",
      type: "Buy",
      category: "Apartment",
      price: "₦17,600,000",
      user: "queen_ubi",
      isFeatured: false,
      status: "Cancelled"
    },
    {
      id: 22,
      street: "Oduduwa Crescent",
      city: "Ile-Ife",
      type: "Rent",
      category: "Apartment",
      price: "₦4,900,000",
      user: "kingston",
      isFeatured: false,
      status: "Completed"
    },
    {
      id: 23,
      street: "Oladipo Diya",
      city: "Abuja",
      type: "Buy",
      category: "Duplex",
      price: "₦31,500,000",
      user: "pretty_liz",
      isFeatured: true,
      status: "Pending"
    },
    {
      id: 24,
      street: "Olosa Street",
      city: "Lagos",
      type: "Rent",
      category: "Apartment",
      price: "₦8,400,000",
      user: "smart_j",
      isFeatured: false,
      status: "Completed"
    },
    {
      id: 25,
      street: "Ribadu Road",
      city: "Abuja",
      type: "Buy",
      category: "Duplex",
      price: "₦42,300,000",
      user: "young_d",
      isFeatured: true,
      status: "Cancelled"
    }
  ];