export const PropertyDetailData = [
  {
    id: 1,
    title: "Palm Harbour Terrace",
    price: "₦1,500,000 / Yearly",
    location: "No. 24 Green Valley Estate, Ifite Awka, Anambra",
    beds: 3,
    baths: 3,
    size: "5x7 m²",
    images: [
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
     
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Palm Harbour Terrace is a breathtaking waterfront property located in the serene Green Valley Estate, Ifite Awka, Anambra. This luxurious 3-bedroom home offers an unparalleled blend of modern elegance and natural beauty, with stunning ocean views and direct access to pristine beaches. The spacious interiors feature high ceilings, large windows, and premium finishes, creating an airy and inviting atmosphere. Residents enjoy a state-of-the-art fitness center, a sparkling infinity pool, and beautifully landscaped gardens ideal for relaxation or entertaining guests. Equipped with smart home technology, including automated lighting and security systems, this property ensures both convenience and safety. Its prime location offers proximity to local amenities, schools, and recreational facilities, making it perfect for families or professionals seeking a tranquil yet connected lifestyle. Whether you're sipping coffee on the balcony or hosting a barbecue in the garden, Palm Harbour Terrace delivers a lifestyle of comfort and sophistication.",
    videoImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "3 Beds" },
      { label: "Bathrooms", value: "3 Baths" },
      { label: "Size", value: "5x7 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "2 Cars" },
      { label: "Property Type", value: "Apartment" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2020" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Modern" },
      { label: "Parking", value: "Private" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Oceanfront" },
      { label: "Flooring", value: "Hardwood" },
    ],
    amenities: [
      { label: "Fitness Center", value: "Yes" },
      { label: "Swimming Pool", value: "Infinity" },
      { label: "Landscaped Gardens", value: "Yes" },
      { label: "Smart Home Technology", value: "Yes" },
      { label: "Security System", value: "24/7" },
      { label: "Air Conditioning", value: "Central" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "Laundry Facilities", value: "In-Unit" },
      { label: "Parking", value: "Private" },
      { label: "Elevator", value: "Yes" },
      { label: "Clubhouse", value: "Yes" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Playground", value: "Nearby" },
      { label: "Concierge", value: "Yes" },
      { label: "Storage", value: "Available" },
    ],
    floorPlans: [
      { title: "First Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Second Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Basement", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.2178496790416!2d7.083824609879577!3d6.2349892937271525!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x104383a198821483%3A0x40608ea62a425869!2sIfite%20Awka%2C%20Anambra!5e0!3m2!1sen!2sng!4v1753510920498!5m2!1sen!2sng",
    reviews: [
      {
        name: "Samuelson Denise",
        date: "19 August 2025",
        comment: "Palm Harbour Terrace is an absolute gem! The ocean views are breathtaking, and the smart home features make daily life so convenient. The fitness center and pool are top-notch, and the location is perfect for accessing local amenities. Highly recommend for anyone seeking luxury and comfort.",
      },
      {
        name: "Chinwe Okeke",
        date: "10 July 2025",
        comment: "Living here has been a dream. The spacious layout and modern amenities like high-speed internet and in-unit laundry make it perfect for my family. The gardens are a great spot for relaxation, and the security system gives peace of mind.",
      },
    ],
    agent: {
      name: "Sara Conor",
      phone: "+234 816 5026 123",
      email: "sara.conor@realestate.com",
      image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 2,
    title: "Luxe City Apartment",
    price: "₦3,200,000 / Yearly",
    location: "Victoria Island, Lagos",
    beds: 4,
    baths: 4,
    size: "8x10 m²",
    images: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Luxe City Apartment in the heart of Victoria Island, Lagos, redefines urban luxury with its expansive 4-bedroom layout and cutting-edge amenities. Nestled in the vibrant business district, this property offers seamless access to top-tier restaurants, shopping malls, and corporate offices. The interiors boast sleek designs with floor-to-ceiling windows, flooding the space with natural light and offering panoramic city views. Residents enjoy a rooftop swimming pool, a state-of-the-art fitness center, and a private garden for relaxation. The smart home system includes automated climate control, security cameras, and high-speed internet, ensuring a modern and secure living experience. With 24/7 concierge services, secure parking, and an elevator, this apartment caters to professionals and families seeking convenience and sophistication in Lagos' bustling metropolis.",
    videoImage: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "4 Beds" },
      { label: "Bathrooms", value: "4 Baths" },
      { label: "Size", value: "8x10 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "2 Cars" },
      { label: "Property Type", value: "Apartment" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2022" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Gourmet" },
      { label: "Parking", value: "Secure" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Cityscape" },
      { label: "Flooring", value: "Marble" },
    ],
    amenities: [
      { label: "Fitness Center", value: "Yes" },
      { label: "Swimming Pool", value: "Rooftop" },
      { label: "Secure Parking", value: "Yes" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "24/7 Security", value: "Yes" },
      { label: "Elevator", value: "Yes" },
      { label: "Garden", value: "Private" },
      { label: "Smart Home System", value: "Yes" },
      { label: "Laundry Facilities", value: "In-Unit" },
      { label: "Air Conditioning", value: "Central" },
      { label: "Concierge", value: "24/7" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Clubhouse", value: "Yes" },
      { label: "Storage", value: "Available" },
      { label: "Spa", value: "On-Site" },
    ],
    floorPlans: [
      { title: "Main Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Upper Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Basement", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.315608775!2d3.4235273!3d6.4299088!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103bf4f1a9b1b3b5%3A0x3e0f4b2b5a5b5b5b!2sVictoria%20Island%2C%20Lagos!5e0!3m2!1sen!2sng!4v1729423245678!5m2!1sen!2sng",
    reviews: [
      {
        name: "Adewale Johnson",
        date: "15 September 2025",
        comment: "Luxe City Apartment is perfect for city living. The rooftop pool and fitness center are fantastic, and the location in Victoria Island is unbeatable. The smart home system makes everything so easy, from controlling lights to security. Highly recommend for professionals!",
      },
      {
        name: "Ngozi Adebayo",
        date: "22 June 2025",
        comment: "This apartment is a masterpiece. The city views are stunning, and the amenities like the concierge and secure parking make life so convenient. The spacious layout is great for my family, and the marble flooring adds a touch of elegance.",
      },
    ],
    agent: {
      name: "Tunde Adeyemi",
      phone: "+234 803 1234 567",
      email: "tunde.adeyemi@realestate.com",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 3,
    title: "Hillside Duplex",
    price: "₦2,850,000 / Yearly",
    location: "Independence Layout, Enugu",
    beds: 5,
    baths: 4,
    size: "10x12 m²",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
"https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
     ],
    description: "Hillside Duplex in the prestigious Independence Layout of Enugu offers an exceptional living experience with its spacious 5-bedroom design and modern architectural excellence. Perched on a gentle slope, this property provides breathtaking views of the surrounding hills and cityscape. The duplex features an open-concept living area with high ceilings, premium finishes, and large windows that flood the interiors with natural light. Residents can enjoy a private garden, a state-of-the-art fitness room, and a secure environment perfect for families. The smart home integration includes automated security systems, climate control, and energy-efficient appliances. Located in a quiet neighborhood yet close to schools, shopping centers, and healthcare facilities, Hillside Duplex combines tranquility with convenience for an ideal family lifestyle in Enugu.",
    videoImage: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "5 Beds" },
      { label: "Bathrooms", value: "4 Baths" },
      { label: "Size", value: "10x12 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "3 Cars" },
      { label: "Property Type", value: "Duplex" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2021" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Modern" },
      { label: "Parking", value: "Private" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Hillside" },
      { label: "Flooring", value: "Ceramic" },
    ],
    amenities: [
      { label: "Private Garden", value: "Yes" },
      { label: "Fitness Room", value: "Yes" },
      { label: "Security System", value: "24/7" },
      { label: "Air Conditioning", value: "Central" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "Swimming Pool", value: "Private" },
      { label: "Laundry Facilities", value: "In-Unit" },
      { label: "Elevator", value: "Yes" },
      { label: "Parking", value: "Private" },
      { label: "Smart Home Technology", value: "Yes" },
      { label: "Clubhouse", value: "Yes" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Playground", value: "Nearby" },
      { label: "Concierge", value: "Yes" },
      { label: "Storage", value: "Available" },
    ],
    floorPlans: [
      { title: "Ground Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Upper Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Basement", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.2178496790416!2d7.483824909879577!3d6.4349892937271525!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x104383a198821483%3A0x40608ea62a425869!2sIndependence%20Layout%2C%20Enugu!5e0!3m2!1sen!2sng!4v1753510920498!5m2!1sen!2sng",
    reviews: [
      {
        name: "Chidi Nwankwo",
        date: "8 November 2025",
        comment: "Hillside Duplex exceeded all our expectations. The hill views are spectacular, and the spacious layout is perfect for our large family. The private garden and fitness room are wonderful additions that we use daily.",
      },
      {
        name: "Grace Okafor",
        date: "25 September 2025",
        comment: "This duplex offers the perfect balance of luxury and comfort. The smart home features make life so convenient, and the security system gives us complete peace of mind. The neighborhood is quiet and family-friendly.",
      },
    ],
    agent: {
      name: "Emeka Nwosu",
      phone: "+234 805 5678 901",
      email: "emeka.nwosu@realestate.com",
      image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 4,
    title: "The Beachfront Villa",
    price: "₦7,500,000 / Yearly",
    location: "Lekki Phase 1, Lagos",
    beds: 6,
    baths: 5,
    size: "12x15 m²",
    images: [
     
            "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
     
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    ],
    description: "The Beachfront Villa in Lekki Phase 1, Lagos, represents the pinnacle of coastal luxury living with its magnificent 6-bedroom design and direct beach access. This architectural masterpiece features expansive living spaces with floor-to-ceiling windows that frame panoramic ocean views and allow natural light to illuminate the elegant interiors. The villa boasts an infinity pool that seems to merge with the ocean, a private home theater, and a luxurious spa for ultimate relaxation. High-end finishes include marble flooring, custom cabinetry, and premium appliances throughout. The property's smart home system integrates security, lighting, and entertainment for seamless control. With its prime beachfront location, residents enjoy private beach access while being minutes away from Lekki's finest restaurants, shopping centers, and entertainment venues. This villa offers an unparalleled lifestyle for those seeking the ultimate in luxury and coastal living.",
    videoImage: "https://images.unsplash.com/photo-1613975932540-5a9540af7719?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "6 Beds" },
      { label: "Bathrooms", value: "5 Baths" },
      { label: "Size", value: "12x15 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "4 Cars" },
      { label: "Property Type", value: "Villa" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2023" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Gourmet" },
      { label: "Parking", value: "Private" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Oceanfront" },
      { label: "Flooring", value: "Marble" },
    ],
    amenities: [
      { label: "Infinity Pool", value: "Yes" },
      { label: "Beach Access", value: "Private" },
      { label: "Home Theater", value: "Yes" },
      { label: "Spa", value: "Yes" },
      { label: "Fitness Center", value: "Yes" },
      { label: "Garden", value: "Landscaped" },
      { label: "Smart Home", value: "Yes" },
      { label: "Security", value: "24/7" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "Laundry", value: "In-Unit" },
      { label: "Concierge", value: "24/7" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Clubhouse", value: "Yes" },
      { label: "Storage", value: "Available" },
      { label: "Wine Cellar", value: "Yes" },
    ],
    floorPlans: [
      { title: "Ground Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Upper Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Basement", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.315608775!2d3.470000314772949!3d6.430000228100001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103bf4f1a9b1b3b5%3A0x3e0f4b2b5a5b5b5b!2sLekki%20Phase%201%2C%20Lagos!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "Bola Adekunle",
        date: "12 December 2025",
        comment: "The Beachfront Villa is absolute perfection! Waking up to ocean views every morning is priceless. The infinity pool and private beach access make every day feel like a vacation. The attention to detail in the design and amenities is remarkable.",
      },
      {
        name: "Jennifer Okoro",
        date: "3 October 2025",
        comment: "This villa redefines luxury living. The home theater and spa are incredible features we use weekly. The security and smart home systems provide complete peace of mind. It's worth every naira for the lifestyle it offers.",
      },
    ],
    agent: {
      name: "Kunle Adebayo",
      phone: "+234 807 2345 678",
      email: "kunle.adebayo@realestate.com",
      image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 5,
    title: "Lakewood Luxury Apartments",
    price: "₦4,200,000 / Yearly",
    location: "Maitama, Abuja",
    beds: 4,
    baths: 3,
    size: "9x11 m²",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
      
       "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80",
       "https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=800&q=80",
 
    ],
    description: "Lakewood Luxury Apartments in the prestigious Maitama district of Abuja offer sophisticated urban living with stunning lake views and premium amenities. These elegant 4-bedroom apartments feature contemporary designs with spacious layouts, high ceilings, and premium finishes that create an atmosphere of refined comfort. The property overlooks a serene lake, providing residents with peaceful water views and a tranquil environment in the heart of the capital city. Residents enjoy access to a state-of-the-art fitness center, swimming pool, and beautifully maintained common areas. The building features advanced security systems, underground parking, and 24/7 concierge services. Located in one of Abuja's most sought-after neighborhoods, Lakewood Apartments provide easy access to government offices, international schools, and upscale shopping centers, making it the perfect choice for diplomats, executives, and families seeking luxury and convenience.",
    videoImage: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "4 Beds" },
      { label: "Bathrooms", value: "3 Baths" },
      { label: "Size", value: "9x11 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "2 Cars" },
      { label: "Property Type", value: "Apartment" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2022" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Modern" },
      { label: "Parking", value: "Underground" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Lake" },
      { label: "Flooring", value: "Hardwood" },
    ],
    amenities: [
      { label: "Lake Views", value: "Yes" },
      { label: "24/7 Security", value: "Yes" },
      { label: "Swimming Pool", value: "Yes" },
      { label: "Fitness Center", value: "Yes" },
      { label: "Underground Parking", value: "Yes" },
      { label: "Concierge Service", value: "24/7" },
      { label: "Air Conditioning", value: "Central" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "Laundry Facilities", value: "In-Unit" },
      { label: "Elevator", value: "Yes" },
      { label: "Clubhouse", value: "Yes" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Playground", value: "Nearby" },
      { label: "Storage", value: "Available" },
      { label: "Spa", value: "On-Site" },
    ],
    floorPlans: [
      { title: "Apartment Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Building Floor Plan", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Amenities Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3940.785553530172!2d7.489722314779185!3d9.057876893553785!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x104e0b2b9c1b1b1b%3A0x1b0b0b0b0b0b0b0b!2sMaitama%2C%20Abuja!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "David Okon",
        date: "18 November 2025",
        comment: "Lakewood Apartments offer the perfect blend of luxury and convenience. The lake views are absolutely stunning, and the concierge service is exceptional. The location in Maitama is ideal for accessing government offices and international schools.",
      },
      {
        name: "Aisha Bello",
        date: "7 September 2025",
        comment: "Living here has been a wonderful experience. The apartments are spacious and well-designed, with high-quality finishes throughout. The security and underground parking give us great peace of mind. Highly recommended for families.",
      },
    ],
    agent: {
      name: "Fatima Aliyu",
      phone: "+234 802 3456 789",
      email: "fatima.aliyu@realestate.com",
      image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 6,
    title: "Garden City Residence",
    price: "₦2,100,000 / Yearly",
    location: "GRA, Benin City",
    beds: 3,
    baths: 2,
    size: "7x9 m²",
    images: [
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    
            "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Garden City Residence in the heart of GRA, Benin City, offers a perfect blend of traditional charm and modern convenience in its elegant 3-bedroom bungalow design. This property is surrounded by lush, mature gardens and features a private courtyard that creates a serene oasis in the city center. The residence boasts spacious interiors with high ceilings, large windows, and traditional architectural elements that pay homage to Benin's rich cultural heritage while incorporating contemporary comforts. The property includes a modern kitchen, updated bathrooms, and ample storage space. Residents enjoy the privacy of a secured compound with 24/7 security, backup power supply, and reliable water systems. Located in one of Benin City's most prestigious neighborhoods, Garden City Residence provides easy access to cultural landmarks, shopping centers, and educational institutions, making it an ideal home for those who appreciate both heritage and modern living.",
    videoImage: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "3 Beds" },
      { label: "Bathrooms", value: "2 Baths" },
      { label: "Size", value: "7x9 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "1 Car" },
      { label: "Property Type", value: "Bungalow" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2018" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Modern" },
      { label: "Parking", value: "Private" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Garden" },
      { label: "Flooring", value: "Ceramic" },
    ],
    amenities: [
      { label: "Private Garden", value: "Yes" },
      { label: "Courtyard", value: "Yes" },
      { label: "Security System", value: "24/7" },
      { label: "Air Conditioning", value: "Central" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "Laundry Facilities", value: "In-Unit" },
      { label: "Parking", value: "Private" },
      { label: "Water Treatment System", value: "Yes" },
      { label: "Backup Generator", value: "Yes" },
      { label: "Maid's Quarters", value: "Yes" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Storage", value: "Available" },
      { label: "Garden Shed", value: "Yes" },
      { label: "Security House", value: "Yes" },
      { label: "Borehole", value: "Yes" },
    ],
    floorPlans: [
      { title: "Main Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Garden Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Property Site Plan", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.315608775!2d5.618000314772949!3d6.330000228100001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1040d3a1b1b1b1b1%3A0x1b0b0b0b0b0b0b0b!2sGRA%2C%20Benin%20City!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "Osaretin Iyare",
        date: "14 October 2025",
        comment: "Garden City Residence is a true gem in Benin City. The private garden and courtyard create such a peaceful atmosphere, and the traditional design elements are beautifully executed. The security and backup systems work flawlessly.",
      },
      {
        name: "Patience Omoregie",
        date: "29 August 2025",
        comment: "This bungalow perfectly balances heritage and modernity. The spacious rooms and high ceilings make it feel so airy and comfortable. The location in GRA is perfect for accessing all parts of the city while enjoying a quiet neighborhood.",
      },
    ],
    agent: {
      name: "Blessing Osagie",
      phone: "+234 806 7890 123",
      email: "blessing.osagie@realestate.com",
      image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 7,
    title: "Skyline Penthouse",
    price: "₦5,800,000 / Yearly",
    location: "Ikoyi, Lagos",
    beds: 5,
    baths: 4,
    size: "11x13 m²",
    images: [
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
       "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Skyline Penthouse in the exclusive Ikoyi neighborhood of Lagos represents the ultimate in urban luxury living with its magnificent 5-bedroom design and panoramic city views. This extraordinary penthouse occupies the entire top floor of a prestigious residential tower, offering unparalleled privacy and sophistication. The residence features floor-to-ceiling windows that frame breathtaking views of Lagos Island, the lagoon, and the Atlantic Ocean beyond. The interior spaces are designed with the highest quality materials, including imported marble, custom millwork, and designer fixtures. A private rooftop terrace provides an ideal space for entertaining, complete with an outdoor kitchen and dining area. The penthouse includes a private elevator entrance, a wine cellar, and a state-of-the-art home theater system. Located in one of Lagos' most coveted addresses, residents enjoy proximity to fine dining, luxury shopping, and corporate headquarters while experiencing the pinnacle of residential luxury and privacy.",
    videoImage: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "5 Beds" },
      { label: "Bathrooms", value: "4 Baths" },
      { label: "Size", value: "11x13 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "3 Cars" },
      { label: "Property Type", value: "Penthouse" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2023" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Gourmet" },
      { label: "Parking", value: "Private" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Panoramic" },
      { label: "Flooring", value: "Marble" },
    ],
    amenities: [
      { label: "Rooftop Terrace", value: "Yes" },
      { label: "Panoramic Views", value: "Yes" },
      { label: "Private Elevator", value: "Yes" },
      { label: "Wine Cellar", value: "Yes" },
      { label: "Home Theater", value: "Yes" },
      { label: "Smart Home System", value: "Yes" },
      { label: "24/7 Security", value: "Yes" },
      { label: "Infinity Pool", value: "Private" },
      { label: "Fitness Center", value: "Private" },
      { label: "Concierge Service", value: "24/7" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Storage", value: "Available" },
      { label: "Spa", value: "Private" },
      { label: "Library", value: "Yes" },
      { label: "Bar", value: "Wet Bar" },
    ],
    floorPlans: [
      { title: "Main Level", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Rooftop Terrace", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Entertainment Level", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.315608775!2d3.435000314772949!3d6.450000228100001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103b8b2b2b2b2b2b%3A0x1b0b0b0b0b0b0b0b!2sIkoyi%2C%20Lagos!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "Segun Adewale",
        date: "22 December 2025",
        comment: "Skyline Penthouse is absolutely spectacular! The panoramic views of Lagos are worth every naira. The private elevator and rooftop terrace make entertaining guests an unforgettable experience. This is urban luxury at its finest.",
      },
      {
        name: "Chioma Nwosu",
        date: "9 November 2025",
        comment: "Living in this penthouse feels like being in a five-star hotel. The attention to detail in the finishes and the smart home integration are exceptional. The concierge service is incredibly responsive and helpful. Truly world-class living.",
      },
    ],
    agent: {
      name: "James Okafor",
      phone: "+234 804 4567 890",
      email: "james.okafor@realestate.com",
      image: "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 8,
    title: "Heritage Mansion",
    price: "₦9,200,000 / Yearly",
    location: "Asokoro, Abuja",
    beds: 7,
    baths: 6,
    size: "15x18 m²",
    images: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Heritage Mansion in the prestigious diplomatic enclave of Asokoro, Abuja, represents the pinnacle of luxury living with its grand 7-bedroom design and exquisite architectural details. This magnificent property sits on an expansive plot surrounded by meticulously landscaped gardens and offers unparalleled privacy and security. The mansion features a classic yet contemporary design with high vaulted ceilings, imported marble flooring, and custom architectural details throughout. The residence includes multiple living areas, a formal dining room that seats twenty, and a state-of-the-art gourmet kitchen with premium appliances. The property boasts a swimming pool, tennis court, and a separate guest house with its own amenities. Advanced security features include a security bunker, perimeter fencing, and 24/7 armed security personnel. Located in Abuja's most exclusive neighborhood, Heritage Mansion offers proximity to embassies, government offices, and international schools, making it the perfect residence for ambassadors, high-ranking officials, and discerning individuals seeking the ultimate in luxury and privacy.",
    videoImage: "https://images.unsplash.com/photo-1600585154340-9e4d947e3a0a?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "7 Beds" },
      { label: "Bathrooms", value: "6 Baths" },
      { label: "Size", value: "15x18 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "5 Cars" },
      { label: "Property Type", value: "Mansion" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2022" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Gourmet" },
      { label: "Parking", value: "Private" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Garden" },
      { label: "Flooring", value: "Marble" },
    ],
    amenities: [
      { label: "Swimming Pool", value: "Olympic" },
      { label: "Tennis Court", value: "Yes" },
      { label: "Home Gym", value: "Yes" },
      { label: "Library", value: "Yes" },
      { label: "Wine Cellar", value: "Yes" },
      { label: "Guest House", value: "Yes" },
      { label: "Staff Quarters", value: "Yes" },
      { label: "Security Bunker", value: "Yes" },
      { label: "Helipad", value: "Yes" },
      { label: "Landscaped Gardens", value: "Yes" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Spa", value: "Private" },
      { label: "Theater", value: "Home" },
      { label: "Bar", value: "Wet Bar" },
      { label: "Elevator", value: "Yes" },
    ],
    floorPlans: [
      { title: "Ground Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "First Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Guest House", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3940.785553530172!2d7.519722314779185!3d9.037876893553785!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x104e0b2b9c1b1b1b%3A0x1b0b0b0b0b0b0b0b!2sAsokoro%2C%20Abuja!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "Ambassador Williams",
        date: "15 January 2026",
        comment: "Heritage Mansion exceeds all expectations for diplomatic living. The security features are comprehensive, and the amenities rival those of luxury resorts. The staff quarters and guest house are perfectly designed for official entertaining.",
      },
      {
        name: "Alhaji Sani",
        date: "3 December 2025",
        comment: "This mansion is truly remarkable. The attention to detail in the construction and finishes is exceptional. The tennis court and swimming pool are used daily by our family, and the library is a peaceful retreat. Worth every investment.",
      },
    ],
    agent: {
      name: "Mohammed Bello",
      phone: "+234 809 0123 456",
      email: "mohammed.bello@realestate.com",
      image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 9,
    title: "Metropolitan Loft",
    price: "₦1,800,000 / Yearly",
    location: "Central Business District, Uyo",
    beds: 2,
    baths: 2,
    size: "6x8 m²",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
     "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Metropolitan Loft in the bustling Central Business District of Uyo offers a sophisticated urban living experience with its stylish 2-bedroom design and industrial-chic aesthetic. This contemporary loft features high ceilings, exposed brick walls, and large factory-style windows that create an open, airy atmosphere flooded with natural light. The open-concept living space seamlessly connects the kitchen, dining, and living areas, making it perfect for both relaxing and entertaining. The loft includes modern amenities such as a fully equipped kitchen with stainless steel appliances, updated bathrooms with premium fixtures, and ample storage solutions. Residents enjoy access to building amenities including a rooftop terrace with city views, a fitness center, and secure parking. Located in the heart of Uyo's business district, Metropolitan Loft provides easy access to offices, restaurants, and entertainment venues, making it the ideal choice for young professionals, couples, and students seeking a modern, convenient urban lifestyle in Akwa Ibom's capital city.",
    videoImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "2 Beds" },
      { label: "Bathrooms", value: "2 Baths" },
      { label: "Size", value: "6x8 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "1 Car" },
      { label: "Property Type", value: "Loft" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2021" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Modern" },
      { label: "Parking", value: "Secure" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "City" },
      { label: "Flooring", value: "Concrete" },
    ],
    amenities: [
      { label: "High Ceilings", value: "Yes" },
      { label: "Open Plan Living", value: "Yes" },
      { label: "Modern Kitchen", value: "Yes" },
      { label: "Security System", value: "24/7" },
      { label: "Air Conditioning", value: "Central" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "Laundry Facilities", value: "In-Unit" },
      { label: "Parking", value: "Secure" },
      { label: "Elevator", value: "Yes" },
      { label: "Rooftop Access", value: "Yes" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Fitness Center", value: "Yes" },
      { label: "Storage", value: "Available" },
      { label: "Concierge", value: "Yes" },
      { label: "Bike Storage", value: "Yes" },
    ],
    floorPlans: [
      { title: "Loft Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Building Floor Plan", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Amenities Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3975.0000000000005!2d7.920000314772949!3d5.030000228100001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1069cd4f1a9b1b3b5%3A0x3e0f4b2b5a5b5b5b!2sCentral%20Business%20District%2C%20Uyo!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "Ekemini Bassey",
        date: "11 October 2025",
        comment: "Metropolitan Loft is perfect for urban living in Uyo. The industrial design with high ceilings and exposed brick gives it such character. The location in CBD means everything is within walking distance. Great value for the amenities offered.",
      },
      {
        name: "Imabong Udoh",
        date: "28 July 2025",
        comment: "I love the open concept and modern feel of this loft. The rooftop access provides amazing views of the city, and the in-unit laundry is so convenient. The security system makes me feel safe living in the city center.",
      },
    ],
    agent: {
      name: "Anietie Williams",
      phone: "+234 808 9012 345",
      email: "anietie.williams@realestate.com",
      image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 10,
    title: "Royal Gardens Estate",
    price: "₦3,500,000 / Yearly",
    location: "GRA, Ibadan",
    beds: 4,
    baths: 3,
    size: "8x10 m²",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Royal Gardens Estate in the prestigious GRA area of Ibadan offers classic elegance and modern comfort in its spacious 4-bedroom detached house design. This magnificent property features traditional colonial architecture with modern updates, set within mature, beautifully landscaped gardens that create a private oasis in the city. The residence boasts high ceilings, large windows, and original architectural details that have been carefully preserved while incorporating contemporary amenities. The house includes multiple living areas, a formal dining room, and a updated kitchen with modern appliances. The property features a secure compound with 24/7 security, ample parking, and additional outbuildings for staff or storage. Located in one of Ibadan's most desirable neighborhoods, Royal Gardens Estate provides easy access to schools, hospitals, and shopping centers while offering the peace and privacy of a secure, gated community. This property represents the perfect blend of historical charm and modern living for families seeking elegance and comfort in Nigeria's largest city.",
    videoImage: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "4 Beds" },
      { label: "Bathrooms", value: "3 Baths" },
      { label: "Size", value: "8x10 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "2 Cars" },
      { label: "Property Type", value: "House" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2015" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Updated" },
      { label: "Parking", value: "Private" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Garden" },
      { label: "Flooring", value: "Hardwood" },
    ],
    amenities: [
      { label: "Mature Gardens", value: "Yes" },
      { label: "Private Compound", value: "Yes" },
      { label: "Security House", value: "Yes" },
      { label: "Borehole Water", value: "Yes" },
      { label: "Backup Generator", value: "Yes" },
      { label: "Air Conditioning", value: "Central" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "Laundry Facilities", value: "In-Unit" },
      { label: "Parking", value: "Private" },
      { label: "Storage Rooms", value: "Yes" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Garden Shed", value: "Yes" },
      { label: "Staff Quarters", value: "Yes" },
      { label: "Water Treatment", value: "Yes" },
      { label: "Security System", value: "24/7" },
    ],
    floorPlans: [
      { title: "Main House", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Outbuilding", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Property Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.315608775!2d3.890000314772949!3d7.380000228100001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x10398d1d1d1d1d1d%3A0x1b0b0b0b0b0b0b0b!2sGRA%2C%20Ibadan!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "Professor Adeyemi",
        date: "17 September 2025",
        comment: "Royal Gardens Estate captures the elegance of old Ibadan with all the modern comforts. The mature gardens are absolutely beautiful and provide such privacy. The high ceilings and hardwood floors maintain the property's historical character perfectly.",
      },
      {
        name: "Funke Alabi",
        date: "4 June 2025",
        comment: "This house is perfect for our family. The secure compound gives us peace of mind, and the spacious rooms accommodate everyone comfortably. The location in GRA is ideal - quiet and peaceful yet close to everything we need.",
      },
    ],
    agent: {
      name: "Yemi Ogunleye",
      phone: "+234 810 2345 678",
      email: "yemi.ogunleye@realestate.com",
      image: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 11,
    title: "Oceanview Condominium",
    price: "₦4,800,000 / Yearly",
    location: "Oniru Beach, Lagos",
    beds: 3,
    baths: 3,
    size: "7x9 m²",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
     "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Oceanview Condominium at Oniru Beach, Lagos, offers an unparalleled coastal living experience with its elegant 3-bedroom design and direct beach access. This premium condominium features floor-to-ceiling windows that frame breathtaking views of the Atlantic Ocean, allowing residents to enjoy spectacular sunrises and ocean breezes from the comfort of their home. The interior spaces are designed with a coastal aesthetic, featuring light-filled rooms, premium finishes, and an open-concept layout that maximizes the ocean views. Residents enjoy exclusive access to a private beach club, infinity pool overlooking the ocean, and a state-of-the-art fitness center. The building features advanced security systems, underground parking, and 24/7 concierge services. Located in the vibrant Oniru neighborhood, this condominium provides easy access to Victoria Island's business district, Lekki's shopping centers, and numerous dining and entertainment options while offering a tranquil beachfront retreat from the city's hustle and bustle.",
    videoImage: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "3 Beds" },
      { label: "Bathrooms", value: "3 Baths" },
      { label: "Size", value: "7x9 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "2 Cars" },
      { label: "Property Type", value: "Condominium" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2022" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Gourmet" },
      { label: "Parking", value: "Underground" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Ocean" },
      { label: "Flooring", value: "Porcelain" },
    ],
    amenities: [
      { label: "Beach Access", value: "Private" },
      { label: "Ocean Views", value: "Yes" },
      { label: "Swimming Pool", value: "Infinity" },
      { label: "Fitness Center", value: "Yes" },
      { label: "Beach Club", value: "Private" },
      { label: "Security", value: "24/7" },
      { label: "Air Conditioning", value: "Central" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "Laundry Facilities", value: "In-Unit" },
      { label: "Underground Parking", value: "Yes" },
      { label: "Concierge", value: "24/7" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Spa", value: "On-Site" },
      { label: "Storage", value: "Available" },
      { label: "Elevator", value: "Yes" },
    ],
    floorPlans: [
      { title: "Apartment Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Building Amenities", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Beach Club Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.315608775!2d3.445000314772949!3d6.420000228100001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103b8b2b2b2b2b2b%3A0x1b0b0b0b0b0b0b0b!2sOniru%20Beach%2C%20Lagos!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "Tola Martins",
        date: "24 November 2025",
        comment: "Oceanview Condominium offers the perfect beach lifestyle in Lagos. Waking up to ocean views never gets old, and the private beach access is incredible. The infinity pool and beach club make every weekend feel like a vacation.",
      },
      {
        name: "Kemi Adewale",
        date: "13 August 2025",
        comment: "This condominium exceeds all expectations. The quality of finishes is exceptional, and the ocean views are absolutely breathtaking. The concierge service is incredibly helpful, and the security gives us complete peace of mind.",
      },
    ],
    agent: {
      name: "Bimpe Ojo",
      phone: "+234 811 3456 789",
      email: "bimpe.ojo@realestate.com",
      image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 12,
    title: "Diplomatic Residence",
    price: "₦6,500,000 / Yearly",
    location: "Katampe Extension, Abuja",
    beds: 5,
    baths: 4,
    size: "10x12 m²",
    images: [
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
     "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Diplomatic Residence in the upscale Katampe Extension of Abuja offers sophisticated living with its elegant 5-bedroom design and comprehensive security features. This prestigious property is designed to meet the highest standards of comfort and security, making it ideal for diplomatic personnel, executives, and high-profile residents. The residence features a contemporary architectural design with clean lines, premium materials, and expansive windows that offer panoramic views of Abuja's cityscape and surrounding hills. The interior spaces include formal living and dining areas, a state-of-the-art gourmet kitchen, and a dedicated home office with secure communications capabilities. The property boasts advanced security systems including perimeter fencing, surveillance cameras, and secure access controls. Residents enjoy a swimming pool, landscaped gardens, and ample parking within a gated compound. Located in one of Abuja's most secure and desirable neighborhoods, Diplomatic Residence provides easy access to government offices, embassies, and international schools while offering the privacy and security required for high-level living.",
 

       videoImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "5 Beds" },
      { label: "Bathrooms", value: "4 Baths" },
      { label: "Size", value: "10x12 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "3 Cars" },
      { label: "Property Type", value: "House" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2021" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Gourmet" },
      { label: "Parking", value: "Secure" },
      { label: "Security", value: "Advanced" },
      { label: "View", value: "Panoramic" },
      { label: "Flooring", value: "Marble" },
    ],
    amenities: [
      { label: "Panoramic Views", value: "Yes" },
      { label: "Advanced Security", value: "Yes" },
      { label: "Swimming Pool", value: "Yes" },
      { label: "Home Office", value: "Secure" },
      { label: "Guest Suite", value: "Yes" },
      { label: "Smart Home System", value: "Yes" },
      { label: "Backup Power", value: "Yes" },
      { label: "Water Treatment", value: "Yes" },
      { label: "Landscaped Grounds", value: "Yes" },
      { label: "Staff Accommodation", value: "Yes" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Wine Storage", value: "Yes" },
      { label: "Library", value: "Yes" },
      { label: "Theater", value: "Media Room" },
      { label: "Elevator", value: "Yes" },
    ],
    floorPlans: [
      { title: "Ground Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "First Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Security Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3940.785553530172!2d7.429722314779185!3d9.067876893553785!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x104e0b2b9c1b1b1b%3A0x1b0b0b0b0b0b0b0b!2sKatampe%20Extension%2C%20Abuja!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "Ambassador Chen",
        date: "19 December 2025",
        comment: "Diplomatic Residence meets all our security and comfort requirements perfectly. The advanced security systems are comprehensive, and the home office is ideal for official work. The panoramic views of Abuja are spectacular.",
      },
      {
        name: "Dr. Aliyu Mohammed",
        date: "7 October 2025",
        comment: "This residence offers the perfect balance of luxury and security. The smart home system makes daily living so convenient, and the backup systems ensure uninterrupted comfort. The staff accommodation is well-designed and functional.",
      },
    ],
    agent: {
      name: "Halima Ibrahim",
      phone: "+234 812 4567 890",
      email: "halima.ibrahim@realestate.com",
      image: "https://images.unsplash.com/photo-1485893086445-ed75865251e0?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 13,
    title: "Urban Studio Apartment",
    price: "₦950,000 / Yearly",
    location: "Surulere, Lagos",
    beds: 1,
    baths: 1,
    size: "4x5 m²",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Urban Studio Apartment in the vibrant Surulere neighborhood of Lagos offers efficient and modern living in its compact 1-bedroom studio design. This smartly designed apartment maximizes every square meter to create a comfortable and functional living space perfect for singles, students, or young professionals. The studio features an open-concept layout that combines the sleeping, living, and dining areas into one cohesive space, with a separate kitchenette and bathroom. The apartment includes built-in storage solutions, modern fixtures, and efficient use of space that makes it feel larger than its actual size. Residents benefit from building amenities including 24/7 security, reliable water supply, backup power generation, and proximity to public transportation. Located in one of Lagos' most accessible neighborhoods, Urban Studio Apartment provides easy access to universities, business districts, and entertainment venues while offering an affordable entry point into the Lagos property market. This studio represents the perfect solution for those seeking convenience, security, and modern living in a prime Lagos location.",
    videoImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "1 Bed" },
      { label: "Bathrooms", value: "1 Bath" },
      { label: "Size", value: "4x5 m²" },
      { label: "Balcony", value: "No" },
      { label: "Garage", value: "Street Parking" },
      { label: "Property Type", value: "Studio" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2020" },
      { label: "Heating", value: "Wall Unit" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Kitchenette" },
      { label: "Parking", value: "Street" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "City" },
      { label: "Flooring", value: "Laminate" },
    ],
    amenities: [
      { label: "Compact Living", value: "Yes" },
      { label: "Modern Kitchenette", value: "Yes" },
      { label: "Security", value: "24/7" },
      { label: "Air Conditioning", value: "Yes" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "Laundry Facilities", value: "Shared" },
      { label: "24/7 Water Supply", value: "Yes" },
      { label: "Backup Generator", value: "Yes" },
      { label: "Proximity to Transport", value: "Yes" },
      { label: "Shopping Centers Nearby", value: "Yes" },
      { label: "Pet Friendly", value: "Limited" },
      { label: "Storage", value: "Built-in" },
      { label: "Elevator", value: "Yes" },
      { label: "Common Area", value: "Yes" },
      { label: "Bike Storage", value: "Yes" },
    ],
    floorPlans: [
      { title: "Studio Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Building Floor Plan", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Amenities Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.315608775!2d3.355000314772949!3d6.500000228100001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103b8b2b2b2b2b2b%3A0x1b0b0b0b0b0b0b0b!2sSurulere%2C%20Lagos!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "Chike Okoli",
        date: "16 September 2025",
        comment: "Urban Studio Apartment is perfect for my needs as a student. The efficient use of space is impressive, and the location in Surulere means everything is within easy reach. The security and backup power are reliable.",
      },
      {
        name: "Amina Yusuf",
        date: "2 July 2025",
        comment: "This studio offers great value for money in Lagos. The modern design makes the small space feel comfortable, and the building amenities like laundry and security make urban living so much easier. Perfect for young professionals.",
      },
    ],
    agent: {
      name: "Chinedu Okoro",
      phone: "+234 813 5678 901",
      email: "chinedu.okoro@realestate.com",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 14,
    title: "Executive Townhouse",
    price: "₦3,800,000 / Yearly",
    location: "Jabi, Abuja",
    beds: 4,
    baths: 3,
    size: "8x10 m²",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Executive Townhouse in the popular Jabi district of Abuja offers modern family living with its spacious 4-bedroom design and community amenities. This contemporary townhouse features a thoughtful layout that maximizes space and functionality across multiple levels, providing privacy and comfort for family living. The residence includes an open-concept main floor with living, dining, and kitchen areas that flow seamlessly together, creating an ideal space for family gatherings and entertaining. The townhouse boasts modern finishes, energy-efficient appliances, and ample storage throughout. Residents enjoy access to community amenities including a swimming pool, children's playground, fitness center, and beautifully maintained common areas. The gated community provides 24/7 security, ample parking, and a sense of community among residents. Located in one of Abuja's most dynamic neighborhoods, Executive Townhouse offers easy access to Jabi Lake Mall, recreational facilities, and major transportation routes while providing a secure and comfortable environment for families and professionals seeking balanced urban living in the capital city.",
    videoImage: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "4 Beds" },
      { label: "Bathrooms", value: "3 Baths" },
      { label: "Size", value: "8x10 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "2 Cars" },
      { label: "Property Type", value: "Townhouse" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2021" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Modern" },
      { label: "Parking", value: "Private" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Community" },
      { label: "Flooring", value: "Ceramic" },
    ],
    amenities: [
      { label: "Community Pool", value: "Yes" },
      { label: "Children's Playground", value: "Yes" },
      { label: "Security", value: "24/7" },
      { label: "Clubhouse", value: "Yes" },
      { label: "Fitness Center", value: "Yes" },
      { label: "Air Conditioning", value: "Central" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "Laundry Facilities", value: "In-Unit" },
      { label: "Parking", value: "Private" },
      { label: "Green Spaces", value: "Yes" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Storage", value: "Available" },
      { label: "Elevator", value: "No" },
      { label: "Basketball Court", value: "Yes" },
      { label: "Barbecue Area", value: "Yes" },
    ],
    floorPlans: [
      { title: "Townhouse Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Community Map", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Amenities Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3940.785553530172!2d7.409722314779185!3d9.077876893553785!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x104e0b2b9c1b1b1b%3A0x1b0b0b0b0b0b0b0b!2sJabi%2C%20Abuja!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "Mr. & Mrs. Bello",
        date: "21 October 2025",
        comment: "Executive Townhouse is perfect for our family. The community amenities like the pool and playground are fantastic for our children, and the security gives us peace of mind. The layout provides plenty of space for everyone.",
      },
      {
        name: "Tunde Okafor",
        date: "8 August 2025",
        comment: "This townhouse offers great value in a prime Jabi location. The modern finishes and energy-efficient features help keep utility costs manageable. The community atmosphere is friendly, and the proximity to Jabi Lake Mall is very convenient.",
      },
    ],
    agent: {
      name: "Grace Okeke",
      phone: "+234 814 6789 012",
      email: "grace.okeke@realestate.com",
      image: "https://images.unsplash.com/photo-1517365830460-955ce3f6b1f7?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 15,
    title: "Heritage Colonial House",
    price: "₦2,700,000 / Yearly",
    location: "Government Reserved Area, Calabar",
    beds: 4,
    baths: 3,
    size: "9x11 m²",
    images: [
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
     "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Heritage Colonial House in the historic Government Reserved Area of Calabar offers a unique blend of historical charm and modern comfort in its elegant 4-bedroom design. This beautifully preserved colonial-era property features classic architectural elements including high ceilings, spacious verandas, and traditional woodwork that have been meticulously maintained while incorporating contemporary amenities. The residence boasts original hardwood floors, large sash windows, and multiple fireplaces that evoke the grandeur of a bygone era. The property includes updated systems for modern living, including a renovated kitchen and bathrooms, while preserving the historical character of the home. Set within mature, landscaped gardens, Heritage Colonial House offers privacy and tranquility in one of Calabar's most prestigious neighborhoods. The location provides easy access to the city's cultural landmarks, business district, and recreational facilities while offering a peaceful retreat from urban life. This property represents a rare opportunity to own a piece of Calabar's history while enjoying the comforts of modern living.",
    videoImage: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "4 Beds" },
      { label: "Bathrooms", value: "3 Baths" },
      { label: "Size", value: "9x11 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "2 Cars" },
      { label: "Property Type", value: "Colonial House" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "1935" },
      { label: "Heating", value: "Fireplace" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Updated" },
      { label: "Parking", value: "Private" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Garden" },
      { label: "Flooring", value: "Hardwood" },
    ],
    amenities: [
      { label: "High Ceilings", value: "Yes" },
      { label: "Spacious Verandas", value: "Yes" },
      { label: "Mature Garden", value: "Yes" },
      { label: "Historical Architecture", value: "Yes" },
      { label: "Security", value: "24/7" },
      { label: "Air Conditioning", value: "Central" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "Laundry Facilities", value: "In-Unit" },
      { label: "Parking", value: "Private" },
      { label: "Storage Rooms", value: "Yes" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Garden Shed", value: "Yes" },
      { label: "Staff Quarters", value: "Yes" },
      { label: "Water Treatment", value: "Yes" },
      { label: "Backup Generator", value: "Yes" },
    ],
    floorPlans: [
      { title: "Main House", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Grounds Layout", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Historical Features", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3975.0000000000005!2d8.330000314772949!3d4.980000228100001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x10683c3c3c3c3c3c%3A0x1b0b0b0b0b0b0b0b!2sGovernment%20Reserved%20Area%2C%20Calabar!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "Professor Ekanem",
        date: "13 November 2025",
        comment: "Heritage Colonial House is a living piece of Calabar's history. The preservation of original features like the hardwood floors and high ceilings is remarkable. The modern updates make it comfortable for daily living while maintaining its historical character.",
      },
      {
        name: "Mrs. Edet",
        date: "30 September 2025",
        comment: "This colonial house offers the perfect blend of history and modern comfort. The spacious verandas are ideal for enjoying Calabar's pleasant weather, and the mature gardens provide such privacy and beauty. A truly special property.",
      },
    ],
    agent: {
      name: "Enoch Bassey",
      phone: "+234 815 7890 123",
      email: "enoch.bassey@realestate.com",
      image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=100&q=80",
    },
  },
  {
    id: 16,
    title: "Riverside Retreat",
    price: "₦2,400,000 / Yearly",
    location: "New GRA, Port Harcourt",
    beds: 3,
    baths: 3,
    size: "6x8 m²",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=800&q=80",
     "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Riverside Retreat in New GRA, Port Harcourt, is a haven of tranquility with stunning river views and modern luxury. This 3-bedroom home features spacious interiors with high-end finishes, including hardwood flooring and large windows that maximize natural light. The property includes a private bar, a fitness room, and a lush garden, perfect for unwinding or hosting guests. Residents benefit from smart home technology, such as automated security and climate control, ensuring a seamless living experience. The location offers easy access to Port Harcourt's business and entertainment hubs, while maintaining a peaceful ambiance. With amenities like a riverfront deck, high-speed internet, and 24/7 security, Riverside Retreat is ideal for those seeking a blend of nature and sophistication in a vibrant city.",
    videoImage: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=800&q=80",
    features: [
      { label: "Bedrooms", value: "3 Beds" },
      { label: "Bathrooms", value: "3 Baths" },
      { label: "Size", value: "6x8 m²" },
      { label: "Balcony", value: "Yes" },
      { label: "Garage", value: "2 Cars" },
      { label: "Property Type", value: "House" },
      { label: "Status", value: "Active" },
      { label: "Year Built", value: "2019" },
      { label: "Heating", value: "Central" },
      { label: "Cooling", value: "Air Conditioning" },
      { label: "Kitchen", value: "Modern" },
      { label: "Parking", value: "Private" },
      { label: "Security", value: "24/7" },
      { label: "View", value: "Riverfront" },
      { label: "Flooring", value: "Hardwood" },
    ],
    amenities: [
      { label: "Bar", value: "Private" },
      { label: "Fitness Room", value: "Yes" },
      { label: "Garden", value: "Yes" },
      { label: "River Views", value: "Yes" },
      { label: "Security", value: "24/7" },
      { label: "Air Conditioning", value: "Central" },
      { label: "High-Speed Internet", value: "Yes" },
      { label: "Laundry Facilities", value: "In-Unit" },
      { label: "Parking", value: "Private" },
      { label: "Elevator", value: "Yes" },
      { label: "Pet Friendly", value: "Yes" },
      { label: "Clubhouse", value: "Yes" },
      { label: "Storage", value: "Available" },
      { label: "Concierge", value: "Yes" },
      { label: "Playground", value: "Nearby" },
    ],
    floorPlans: [
      { title: "Main Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Upper Floor", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
      { title: "Basement", image: "https://images.unsplash.com/photo-1616627670274-1647e3e9c8f7?auto=format&fit=crop&w=800&q=80" },
    ],
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3975.0000000000005!2d7.030000314772949!3d4.830000228100001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1069cd4f1a9b1b3b5%3A0x3e0f4b2b5a5b5b5b!2sNew%20GRA%2C%20Port%20Harcourt!5e0!3m2!1sen!2sng!4v1699999999999!5m2!1sen!2sng",
    reviews: [
      {
        name: "Emeka Nwosu",
        date: "5 October 2025",
        comment: "Riverside Retreat is a perfect blend of peace and luxury. The river views are stunning, and the private bar is a great touch for entertaining. The smart home features and secure environment make it ideal for families. Highly recommend!",
      },
      {
        name: "Fatima Ibrahim",
        date: "12 August 2025",
        comment: "This property is a hidden gem in Port Harcourt. The garden and fitness room are fantastic, and the location is perfect for accessing the city while enjoying a quiet retreat. The staff and security team are top-notch.",
      },
    ],
    agent: {
      name: "Amaka Okonkwo",
      phone: "+234 809 9876 543",
      email: "amaka.okonkwo@realestate.com",
      image: "https://images.unsplash.com/photo-1517365830460-955ce3f6b1f7?auto=format&fit=crop&w=100&q=80",
    },
  },
];