export const userPropertiesData = [
    {
      id: 1,
      status: ["For sale", "New Listing", "Virtual Tour", "Lekki", "Logos"],
      price: "#80,000,00",
      paymentType: "Full Payment",
      title: "4 Bedroom Luxury Penthouse with Ocean View",
      location: "Lekki Logos",
      wishlistCount: 120,
      downPayment: "#2000,000",
      downPaymentTime: "One Time",
      installments: "#54,166,667",
      installmentCount: 12,
      firstPaymentDate: "01-11-2024",
    },
    {
      id: 2,
      status: ["For sale", "For Rent", "Open House", "Awka", "Anambra"],
      price: "#200,000",
      paymentType: "7 Payments",
      title: "3 Bedroom Commercial Villa in Tempsite Awka",
      location: "Awka Anambra",
      wishlistCount: 50,
      downPayment: "#5500",
      downPaymentTime: "One Time",
      installments: "#5500",
      installmentCount: 12,
      firstPaymentDate: "17-09-2025",
    },
    {
      id: 3,
      status: ["For sale", "Land", "Distress Sale", "GRA Phase 2", "Rivers"],
      price: "#95,000,000",
      paymentType: "6 Payments",
      title: "2 Plots of Fenced Land with C of O",
      location: "Port Harcourt Rivers",
      wishlistCount: 30,
      downPayment: "#4,000,000",
      downPaymentTime: "One Time",
      installments: "#11,000,000",
      installmentCount: 5,
      firstPaymentDate: "15-12-2024",
    },
  ];