 export const UserInvestmentsCategoryData = [
    {
      image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
      status: "Open for Investors",
      statusBg: "bg-white",
      title: "Residential Buildings",
      description: "Invest in apartments, duplexes, and smart homes for best returns",
      roi: "ROI : 15-20% P.A",
      duration: "Duration 12 Months",
      fundingProgress: 75,
      percentComplete: 75,
      amountRaised: "₦30M Raised",
      goalAmount: "₦50M Goal",
      investors: "54 Investors",
      riskLevel: "Medium Risk",
      riskColor: "text-yellow-600",
      minAmount: "₦1,250,000"
    },
    {
      image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80",
      status: "In Development",
      statusBg: "bg-white",
      title: "Commercial Projects",
      description: "Invest in apartments, duplexes, and smart homes for best returns",
      roi: "ROI : 15-20% P.A",
      duration: "Duration 12 Months",
      fundingProgress: 75,
      percentComplete: 75,
      amountRaised: "₦30M Raised",
      goalAmount: "₦50M Goal",
      investors: "54 Investors",
      riskLevel: "Hire Risk",
      riskColor: "text-red-600",
      minAmount: "₦1,250,000"
    },
    {
      image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
      status: "Foundation Complete",
      statusBg: "bg-white",
      title: "Estate Development",
      description: "Invest in apartments, duplexes, and smart homes for best returns",
      roi: "ROI : 15-20% P.A",
      duration: "Duration 12 Months",
      fundingProgress: 75,
      percentComplete: 75,
      amountRaised: "₦30M Raised",
      goalAmount: "₦50M Goal",
      investors: "54 Investors",
      riskLevel: "low Risk",
      riskColor: "text-green-600",
      minAmount: "₦1,250,000"
    },
    {
      image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&q=80",
      status: "Planting Season",
      statusBg: "bg-white",
      title: "Agricultural Investment",
      description: "Invest in sustainable farming projects for steady returns",
      roi: "ROI : 15-20% P.A",
      duration: "Duration 12 Months",
      fundingProgress: 60,
      percentComplete: 60,
      amountRaised: "₦30M Raised",
      goalAmount: "₦50M Goal",
      investors: "54 Investors",
      riskLevel: "Medium Risk",
      riskColor: "text-yellow-600",
      minAmount: "₦1,250,000"
    },
    {
      image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80",
      status: "Pre-construction",
      statusBg: "bg-white",
      title: "Global Ventures",
      description: "Invest in international projects with high growth potential",
      roi: "ROI : 15-20% P.A",
      duration: "Duration 12 Months",
      fundingProgress: 45,
      percentComplete: 45,
      amountRaised: "₦30M Raised",
      goalAmount: "₦50M Goal",
      investors: "54 Investors",
      riskLevel: "Hire Risk",
      riskColor: "text-red-600",
      minAmount: "₦1,250,000"
    },
    {
      image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
      status: "Roofing Complete",
      statusBg: "bg-white",
      title: "Mixed-Use Development",
      description: "Invest in commercial and residential mixed developments",
      roi: "ROI : 15-20% P.A",
      duration: "Duration 12 Months",
      fundingProgress: 85,
      percentComplete: 85,
      amountRaised: "₦30M Raised",
      goalAmount: "₦50M Goal",
      investors: "54 Investors",
      riskLevel: "low Risk",
      riskColor: "text-green-600",
      minAmount: "₦1,250,000"
    }
  ];